DROP TABLE IF EXISTS BOOK, JUMP;

CREATE TABLE BOOK(TITLE TEXT,
				PRIMARY KEY(TITLE)
				 ); 

CREATE TABLE PAGES(PAGE_NUMBER INTEGER,
				TITLE TEXT,
				CONTENT TEXT
				PRIMARY KEY(TITLE, PAGE_NUMBER),
				FOREIGN KEY(TITLE) REFERENCES (BOOK)
				 ); 

CREATE TABLE JUMP(TITLE TEXT,
				PAGE_NUMBER INTEGER,
				JUMP_TO INTEGER)