DROP TABLE IF EXISTS PLANTS;
DROP TABLE IF EXISTS EVENTS;
DROP TABLE IF EXISTS ATTRIBUTES;

CREATE TABLE PLANTS(NAME TEXT,
				LATIN TEXT,
				VENDOR TEXT,
				PRIMARY KEY(NAME)
				 ); 

CREATE TABLE EVENTS(TYPE INTEGER,
				DATE_ACTIONED TEXT,
				PLANT_NAME TEXT,
				SIZE INTEGER,
				ID INTEGER,
				LABOUR REAL,
				DURATION REAL,
				COST REAL,
				UNIT TEXT,
				PRIMARY KEY(TYPE, DATE_ACTIONED, PLANT_NAME),
				FOREIGN KEY(PLANT_NAME) REFERENCES PLANTS(NAME)
				 ); 

CREATE TABLE ATTRIBUTES(PLANT_NAME TEXT,
				ATTRIBUTE_NAME INTEGER,
				VALUE TEXT,
				UNITS TEXT,
				PRIMARY KEY(PLANT_NAME, ATTRIBUTE_NAME));